import React from 'react';
import { useLocation, Link } from 'react-router-dom';

/**
 * ConfirmedBooking - confirmation page shown after a successful table reservation
  */
  function ConfirmedBooking() {
    const location = useLocation();
      const bookingData = location.state?.bookingData;

        return (
            <main className="confirmed-booking" aria-label="Booking Confirmed">
                  <div className="confirmed-container">
                          <div className="confirmed-icon" aria-hidden="true" role="img">
                                    Booking Confirmed!
                                            </div>
                                                    <h1>Your reservation is confirmed!</h1>
                                                            <p className="confirmed-message">
                                                                      Thank you for choosing Little Lemon. We look forward to seeing you!
                                                                              </p>

                                                                                      {bookingData && (
                                                                                                <section
                                                                                                            className="booking-details"
                                                                                                                        aria-label="Your booking details"
                                                                                                                                  >
                                                                                                                                              <h2>Booking Details</h2>
                                                                                                                                                          <dl>
                                                                                                                                                                        {bookingData.name && (
                                                                                                                                                                                        <>
                                                                                                                                                                                                          <dt>Name:</dt>
                                                                                                                                                                                                                            <dd>{bookingData.name}</dd>
                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                        {bookingData.date && (
                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                          <dt>Date:</dt>
                                                                                                                                                                                                                                                                                                                            <dd>
                                                                                                                                                                                                                                                                                                                                                {new Date(bookingData.date).toLocaleDateString('en-US', {
                                                                                                                                                                                                                                                                                                                                                                      weekday: 'long',
                                                                                                                                                                                                                                                                                                                                                                                            year: 'numeric',
                                                                                                                                                                                                                                                                                                                                                                                                                  month: 'long',
                                                                                                                                                                                                                                                                                                                                                                                                                                        day: 'numeric',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </dd>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {bookingData.time && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <dt>Time:</dt>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <dd>{bookingData.time}</dd>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {bookingData.guests && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <dt>Guests:</dt>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <dd>{bookingData.guests}</dd>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {bookingData.occasion && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <dt>Occasion:</dt>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <dd>{bookingData.occasion}</dd>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {bookingData.email && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <dt>Confirmation sent to:</dt>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <dd>{bookingData.email}</dd>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </dl>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="confirmed-actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link to="/" className="btn btn-primary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Return to Home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link to="/booking" className="btn btn-secondary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Make Another Reservation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default ConfirmedBooking;
